version: '3.8'
services:
  laravel-docker:
    container_name: Rentella_app
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
      - 9000:80
    networks:
      - keycloak-network
  vue:
    container_name: vue
    build:
      context: ../../web/
      dockerfile: Dockerfile
    ports:
      - "5173:8000"
    volumes:
      - ../../web/:/var/www/html/app
      - /var/www/html/app/node_modules
    networks:
      - keycloak-network
  cors:
    build:
      context: ./
      dockerfile: cors.Dockerfile
    container_name: cors
    ports:
      - "4545:80"
    networks:
      - keycloak-network
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Rentella_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - keycloak-network
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    networks:
      - keycloak-network
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    volumes:
      - ../themes/Rentella:/opt/keycloak/themes/Rentella
      - keycloak_standalone_data:/opt/jboss/keycloak/standalone/data
      - keycloak_standalone_deployments:/opt/jboss/keycloak/standalone/deployments
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_USER: user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_PASSWORD: pass
    depends_on:
      - postgres
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
volumes:
  postgres_data:
  keycloak_standalone_data:
  keycloak_standalone_deployments:
